### PR TITLE
Add three.js preview.

### PR DESCRIPTION
**Pull request by donmccurdy**
Manifest looks good! 🙂

Haven't spent any time looking into the errors or tweaking lights yet, but here's a bit of code to render everything in three.js.

Demo: https://cdn.rawgit.com/donmccurdy/glTF-Asset-Generator/feat-threejs-preview/Preview/three.js/index.html

screen shot 2018-01-30 at 3 51 21 pm

### CODE REVIEW

**Comment by bghgary** [comment]
I'm planning on moving the preview folder to https://github.com/bghgary/glTF-Assets-Viewer. The idea is that we will add some links to each of the README of each folder and it will show the results in various engines.

**Comment by bghgary** [comment]
Though, I wasn't aware of https://cdn.rawgit.com. That might change things.

**Comment by donmccurdy** [comment]
Cool! Yeah up to you what if anything to do with this. I'm looking forward to debugging the handful that aren't showing up, great set of test cases here. I'll be traveling for the next ~week so won't be getting to this more until after that.

**Comment by bghgary** [comment]
@donmccurdy We've talked about how each engine will do this kind of testing in their own repo. Can we close this?

**Comment by donmccurdy** [comment]
Sounds good 👍

**Pull request closed without merging**
