### PR TITLE
Create models that use PBR materials textures

### PR DESCRIPTION
**Pull request by stevk**
The pbrMetallicRoughness test now includes both BaseColorTexture and MetallicRoughnessTexture attributes.

This starts to address issue #14 and a small amount of work was done on #11 

This change expands the number of models being created to a whopping 4721.

### CODE REVIEW

**Comment by kcoley** [comment]
I tried running this, but got an System.IO.PathTooLongException.

It conked out on this asset file name:

> "BaseColorFactor-MetallicFactor-RoughnessFactor-BaseColorTexture-Source-Sampler-TexCoord-Name-MetallicRoughnessTexture-Source-Sampler-TexCoord-Name"

>

**Comment by kcoley** [comment]
Looks like it's because my running directory folder path is 124 chars, and the file name is 149 chars, which exceeds the 260 limit.  I can try running this in a different directory.

**Comment by kcoley** [comment]
Runs fine in a shorter directory path.  Since it's not heavily being used by many people, it's probably okay for now.

**Comment by stevk** [comment]
I was worried that we'd run into that issue #11 . I'll work on a fix in my next PR, since it is only going to get worse as we go along.

**Pull request merged**
