### PR TITLE
Implement Primitive Attributes Test

### PR DESCRIPTION
**Pull request by stevk**
Implemented a test for Primitive attributes.

### CODE REVIEW

**Comment by stevk** [comment]
This code isn't completely done yet, but most of the work left is review and tweaks.

- [ ] Need a fix for #111 
- [ ] Verify models are working/rendering as expected
- [ ] Double check log output is formatted correctly

**Comment by stevk** [comment]
https://gist.github.com/stevk/caf93075a584d66a0e5f848c2e94798a

**Comment by stevk** [comment]
I'm thinking that normal/tangent doesn't make sense without a texture/uv set (e.g. basecolortexture). Is this the case?

**Comment by kcoley** [comment]
It could be possible to apply a constant basecolorfactor and use the normal/tangent.  Though without either basecolorfactor or basecolortexture, I agree it would not make much sense.

**Comment by stevk** [comment]
This PR should be ready to complete.

**Comment by kcoley** [comment]
I may need to add in the byte padding update so the numbers should be correct for Model 11 (should show 8 bytes instead of 6).  I'll set that PR up

**Comment by kcoley** [comment]
Can you add two more tests like PrimitiveAttributes1, but using all UNSIGNED_BYTE and all UNSIGNED_SHORT for both the TEXCOORDs and COLOR?

**Comment by stevk** [comment]
Yup, I can do that.

**Comment by stevk** [comment]
combinations of vec3 vs vec4 with that as well?

For example:
Model 1:
TexCoord0_Short
TexCoord1_Short
Color_Vec3_Short

Model 2:
TexCoord0_Short
TexCoord1_Short
Color_Vec4_Short

**Comment by stevk** [comment]
Combos added and gist updated

**Comment by stevk** [comment]
- [ ] Fix the md label "Normal Tangent" to be more human readable

**Comment by stevk** [comment]
Last commit changed the MD for materials as well.

https://gist.github.com/stevk/caf93075a584d66a0e5f848c2e94798a

https://gist.github.com/stevk/6586744c3b3931f73494c4f56f20e010

**Comment by stevk** [comment]
Updated PrimitiveAttribute gist
https://gist.github.com/stevk/caf93075a584d66a0e5f848c2e94798a

**Pull request merged**
