### PR TITLE
Split some tests, rename the tests/folders, and improve the MD log's formatting

### PR DESCRIPTION
**Pull request by stevk**
Splitting up the materials test into materials and PBR gives us md files that are readable without scrolling. The worst side effect is probably that testing alpha and basecolorfactor together is a little awkward with this change.

This increases our total number of models by 2, due to the additional 'No values' and 'all values' models.

Materials
https://gist.github.com/stevk/686af5e364c3bfa430922ec77fa695eb

PBR
https://gist.github.com/stevk/fe62b3971bca91f07de65fe426240edf

This issue is tracked in #135

### CODE REVIEW

**Comment by kcoley** [comment]
- [ ] Use index and just numbers for the model names and header. center.
- [ ] Revert 'with' and just drop normal from tangent
- [ ] Try with smaller text side on headers (sub)

**Comment by stevk** [comment]
Made the requested changes to the MD logs. Without the smaller header text, the Materials test log is just slightly too larger. All of the cells are visible, but the far right border is cut off.

Materials:
https://gist.github.com/stevk/686af5e364c3bfa430922ec77fa695eb

PBR:
https://gist.github.com/stevk/fe62b3971bca91f07de65fe426240edf

Primitive Attributes:
https://gist.github.com/stevk/e9387e999f90d0e8c0d0fdb51f570d7f

**Comment by bghgary** [comment]
We discussed this offline. Let's split alpha properties and double sided into its own table (remember to have a normal texture set for this). Also, include combinations for double sided (true/false) with alpha mode.

**Comment by stevk** [comment]
Materials:
https://gist.github.com/stevk/686af5e364c3bfa430922ec77fa695eb

Alphas:
https://gist.github.com/stevk/692942f9757401eea3e9db784ff3ea5e

PBRs:
https://gist.github.com/stevk/fe62b3971bca91f07de65fe426240edf

PrimitiveAttributes:
https://gist.github.com/stevk/e9387e999f90d0e8c0d0fdb51f570d7f

Samplers:
https://gist.github.com/stevk/6dee698b6e0317a84617c98479c4d972

**Comment by bghgary** [comment]
I'm not sure the first section should be a 2D table. There should only be one set of values, right?

**Comment by stevk** [comment]
Yes, only one set of values per attribute for that first section. What might work better, a list?

**Comment by bghgary** [comment]
A table is fine, but it should probably expand down instead of right.

**Comment by stevk** [comment]
Had to use HTML to get it to work.

https://github.com/bghgary/glTF-Asset-Generator/blob/77bfaaf7f4d692a1715d0e7d796e1ec88b5ceb22/GeneratedAssets/Samplers/README.md

**Comment by bghgary** [comment]
Looks good 👍

**Comment by bghgary** [comment]
Might be too big though. People who want to see the details can just click on it.

**Comment by stevk** [comment]
Half size:
https://github.com/bghgary/glTF-Asset-Generator/blob/2b75da3421359f43017064789c7e26bd71e7f2b2/GeneratedAssets/Samplers/README.md

**Comment by bghgary** [comment]
Hmm, I'm thinking restrict it to the height instead of width now. If you put that size texture everywhere in the table, it will make the table have lots of different row height, which will probably make it harder to read.

**Comment by stevk** [comment]
Halved the size again, and locked the height instead of width.

https://github.com/bghgary/glTF-Asset-Generator/blob/42db68721ff1549f5456feebc3ee9a46ec0641f8/GeneratedAssets/Samplers/README.md

**Comment by bghgary** [comment]
That size seems good 👍 What does it look like when there are textures in the table? Some rows will have textures and some won't.

**Comment by stevk** [comment]
I'll know here in a minute. I'm working on getting everything to display its values right now, but arrays of vectors are being a pain to convert into something readable.

**Comment by stevk** [comment]
Alphas:
https://gist.github.com/stevk/692942f9757401eea3e9db784ff3ea5e

Materials:
https://github.com/bghgary/glTF-Asset-Generator/blob/b47eec14e14cdbe75b898085a17d06d8a738659d/GeneratedAssets/Materials/README.md

MetallicRoughtnessMaterial:
https://github.com/bghgary/glTF-Asset-Generator/blob/b47eec14e14cdbe75b898085a17d06d8a738659d/GeneratedAssets/MetallicRoughnessMaterial/README.md

PrimitiveAttributes:
https://gist.github.com/stevk/e9387e999f90d0e8c0d0fdb51f570d7f

Samplers:
https://gist.github.com/stevk/6dee698b6e0317a84617c98479c4d972

**Comment by bghgary** [comment]
Discussed offline:
- Occlusion texture in PrimitiveAttributes should be a normal texture
- Use lowercase naming in for normalized unsigned short/byte and just use short/byte with a note on top that says they are all normalized unsigned.

**Comment by bghgary** [comment]
Rename to:
Material_Alpha
Material_MetallicRoughness
Primitive_Attribute
Texture_Sampler

**Comment by stevk** [comment]
Material:
https://github.com/bghgary/glTF-Asset-Generator/blob/6c9cb48dd485f37fb362098e66a5094ba05f5878/GeneratedAssets/Materials/README.md

Material_Alpha:
https://gist.github.com/stevk/692942f9757401eea3e9db784ff3ea5e

Material_MetallicRoughness:
https://github.com/bghgary/glTF-Asset-Generator/blob/b47eec14e14cdbe75b898085a17d06d8a738659d/GeneratedAssets/MetallicRoughnessMaterial/README.md

Primitive_Attribute:
https://gist.github.com/stevk/e9387e999f90d0e8c0d0fdb51f570d7f

Texture_Sampler:
https://gist.github.com/stevk/6dee698b6e0317a84617c98479c4d972

**Comment by bghgary** [comment]
- No need for `<br/>` between VectorX and Type in Primitive_Attribute
- "All values of Byte and Short are normalized unsigned" isn't necessary for tables that don't use them.

Consider changing the text for the first table from
> The first table contains attributes that are explicitly set in every model generated by this test.

to
> The following table shows the properties that are set for every model.

And consider changing the text for the second table from
> The following table shows the properties that are set for a given model.

**Comment by stevk** [comment]
Material:
https://github.com/bghgary/glTF-Asset-Generator/blob/59747cd8efd6ebc26fd6a39d2db720c8c3b43d4b/GeneratedAssets/Materials/README.md

Material_Alpha:
https://gist.github.com/stevk/692942f9757401eea3e9db784ff3ea5e

Material_MetallicRoughness:
https://github.com/bghgary/glTF-Asset-Generator/blob/59747cd8efd6ebc26fd6a39d2db720c8c3b43d4b/GeneratedAssets/MetallicRoughnessMaterial/README.md

Primitive_Attribute:
https://gist.github.com/stevk/e9387e999f90d0e8c0d0fdb51f570d7f

Texture_Sampler:
https://gist.github.com/stevk/6dee698b6e0317a84617c98479c4d972

**Comment by stevk** [comment]
The index number for each model is now a link to the .gltf file for the model. Just a raw view of the code. Models 0 and 1 are set up in this example:
https://github.com/bghgary/glTF-Asset-Generator/blob/18c47ae2dbb510b77c410982c4c147249d901edc/GeneratedAssets/MetallicRoughnessMaterial/README.md

**Pull request merged**
