### PR TITLE
Node model groups

### PR DESCRIPTION
**Pull request by stevk**
Model groups for performing transforms on nodes, and negative scale. 

[Node_Attribute](https://github.com/stevk/glTF-Asset-Generator/blob/stevk/node/Output/Node_Attribute/README.md)

[Node_NegativeScale](https://github.com/stevk/glTF-Asset-Generator/blob/stevk/node/Output/Node_NegativeScale/README.md)

### CODE REVIEW

**Comment by stevk** [comment]
I've added Node_Material, which should address testing the use of a mesh and a material without vertex colors in the same model as one that does use vertex colors.

**Comment by stevk** [comment]
For context, this is what the raw matrix data is looking like

image

**Comment by kcoley** [comment]
- The links for Node_Attribute and Node_Material do not seem to be working
 - Is it possible to display the matrices without the brackets and M: ?

**Comment by stevk** [comment]
I've update the links in this PR. I'll look into reformatting matrices.

**Pull request merged**
