### PR TITLE
Add models for v0.2

### PR DESCRIPTION
**Pull request by stevk**

### CODE REVIEW

**Comment by kcoley** [comment]
Which models are being added for this PR?

**Comment by stevk** [comment]
These were the models we reviewed during yesterday's meeting. So the new test model sets are:
Primitive_Attribute
Texture_Sampler

We've also split one of the previous sets in to new sets:
Material_Alpha
Material

And all of the test model sets have had individual models added/removed.

**Comment by stevk** [comment]
These properties are not resulting in visible changes. 

Material
- Normal Scale
- Occlusion Strength

Material-Alpha
- Blend vs Mask
- Mask w/ factor

**Comment by bghgary** [comment]
Closing. v0.2 has been committed directly.

**Pull request closed without merging**
