### PR TITLE
Change Mesh_Primitives to test having two primitives with different materials

### PR DESCRIPTION
**Pull request by stevk**
Changes this model group to only set the Base Color Factor attribute, and add in some models where the primitives are assigned different materials.

Fix for #370 

[Mesh_Primitives](https://github.com/stevk/glTF-Asset-Generator/blob/twomats/Output/Mesh_Primitives/README.md)

### CODE REVIEW

**Comment by bghgary** [comment]
This table is very confusing to me. I think you should put the two materials on the top and the table should only have two columns that indicate which material is used.

**Comment by stevk** [comment]
@bghgary The table has been simplified. Are there any models you want added?

**Comment by bghgary** [comment]
Update baseColorFactor values to [0, 1, 0, 1] and [0, 0, 1, 1]. No need for alpha and no need for fractions.

**Comment by stevk** [comment]
@bghgary Updates made.

**Pull request merged**
