### PR TITLE
Change readme tables to be in order of ascending complexity, and Vertex > Texture > Factor

### PR DESCRIPTION
**Pull request by stevk**
Updates the following model groups so that the readme and models are in order of ascending complexity. 
Fix for #366

[Material](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material/README.md)

[Mesh_Primitives](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Mesh_Primitives/README.md)

[Mesh_PrimitivesUV](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Mesh_PrimitivesUV/README.md)

[Texture_Sampler](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Texture_Sampler/README.md)

[Material_Doublesided](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_Doublesided/README.md)

[Primitive_Attribute](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Primitive_Attribute/README.md)

[Material_MetallicRoughness](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_MetallicRoughness/README.md)

[Material_SpecularGlossiness](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_SpecularGlossiness/README.md)

[Node_NegativeScale](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Node_NegativeScale/README.md)

[Material_AlphaMask](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_AlphaMask/README.md)

[Material_AlphaBlend](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_AlphaBlend/README.md)

### CODE REVIEW

**Comment by kcoley** [comment]
- [ ] Fix bug in texture labels for Mesh_PrimitivesUV

**Comment by stevk** [comment]
Updates have been made. Check it out.

**Comment by kcoley** [comment]
- [ ] move vertex normals to the table in negative scale
- [ ] add models without normals

**Comment by stevk** [comment]
Updates have been made.

[Node_NegativeScale](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Node_NegativeScale/README.md)

[Primitive_Attribute](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Primitive_Attribute/README.md)

[Material_AlphaMask](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_AlphaMask/README.md)

[Material_AlphaBlend](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_AlphaBlend/README.md)

[Material_MetallicRoughness](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_MetallicRoughness/README.md)

[Material_SpecularGlossiness](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_SpecularGlossiness/README.md)

**Comment by kcoley** [comment]
- [ ] Material_SpecularGlossiness - set SpecularFactor override to 0,0,0 for the vertex color model
- [ ] Material_AlphaMask - move the base color texture to required properties
- [ ] @bghgary - What do you think about negative scale intersecting reference plane?

**Comment by stevk** [comment]
Updated

[Material_SpecularGlossiness](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_SpecularGlossiness/README.md)

[Material_AlphaMask](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Material_AlphaMask/README.md)

[Node_NegativeScale](https://github.com/stevk/glTF-Asset-Generator/blob/tableorder/Output/Node_NegativeScale/README.md)

**Pull request merged**
