### PR TITLE
Per test, create md table of models and their attributes

### PR DESCRIPTION
**Pull request by stevk**
Review the output please. 

I know that https://stackedit.io/editor allows viewing the file, and there are VS2014 viewers as well.

Link to the format guide: [https://help.github.com/categories/writing-on-github](https://help.github.com/categories/writing-on-github)

### CODE REVIEW

**Comment by bghgary** [comment]
Can you create a gist with the output?

**Comment by stevk** [comment]
https://gist.github.com/stevk/6586744c3b3931f73494c4f56f20e010

Columns would probably look better centered. Adding that...

**Comment by stevk** [comment]
Updated code and gist

**Comment by bghgary** [comment]
A few suggestions:
- Make AlphaMode one column with the mode as the text of the column value.
- Format column name with spaces based on capitalization so that column widths are not as big.
- Don't show attributes that are not relevant to the permutation matrix and verify that texture permutations are actually fine (i.e. Materials_7 and 8).

**Comment by stevk** [comment]
Materials md: https://gist.github.com/stevk/6586744c3b3931f73494c4f56f20e010

Sampler md: https://gist.github.com/stevk/dc504f6f8106941af42b083f79a73120

**Comment by stevk** [comment]
- [ ] Create empty set, and make it first
- [ ] remove opaque

**Comment by bghgary** [comment]
The sampler table shows values that are the defaults which won't get written out to the file. Can you double check them?

**Comment by stevk** [comment]
No need to change the sampler full set model. MagFilter and MinFilter don't have default values, and the default values of WrapS and WrapT are Repeat (model is using Clap_To_Edge).

**Comment by stevk** [comment]
This PR fixes bugs #77 and #39

**Pull request merged**
